### ISSUE TITLE
请问怎么在阿里云上部署呢？

### ISSUE THREAD

**Issue by andeyeluguo** [Xilinx/ml-suite#18]
你好，我是一位来自中国的用户，使用的是中国阿里云的服务器。我看你们官网上写着可以在阿里云上部署。请问怎么部署呢？

**Comment by hqwgeorge** [comment]
are you using Aliyun F3? please talk to Aliyun for more details about xfdnn porting to aliyun as well.

**Comment by wilderfield** [comment]
This software library does not support the Alibaba cloud at the moment.
