### ISSUE TITLE
VCU118 support

### ISSUE THREAD

**Issue by NIIAS3050** [Xilinx/ml-suite#21]
Hi.
Is it possible to use ml-suite with VCU118 kit(https://www.xilinx.com/products/boards-and-kits/vcu118.html)?

**Comment by kamranjk** [comment]
Hi,

We currently don't have support for the VCU118. The VCU1525, also has the same FPGA as the VCU118, if that is an option for you to try. You can also try the ML Suite on Cloud services like, Nimbix and AWS. 

Thanks,
Kamran
