### ISSUE TITLE
Benchmark White Paper Link Broken

### ISSUE THREAD

**Issue by jchang-endiag** [Xilinx/ml-suite#28]
In [How does FPGA compare to CPU and GPU acceleration](https://github.com/Xilinx/ml-suite/blob/master/docs/tutorials/faq.md#how-does-fpga-compare-to-cpu-and-gpu-acceleration) there a [See white paper for benchmark](https://www.xilinx.com/) which goes to Xilinx's main page.  Could someone fix this link to the correct white paper?

**Comment by kamranjk** [comment]
Hi,

The whitepaper with comparison results will be coming soon and will be published next month. If you have any specific questions, I can try to help out over email? 

thanks,
Kamran

**Comment by adu81020799** [comment]
Okay Thank kyou.

**Comment by kamranjk** [comment]
https://www.xilinx.com/support/documentation/white_papers/wp504-accel-dnns.pdf
