### ISSUE TITLE
Video stream input to YOLO2 with ML-Suite

### ISSUE THREAD

**Issue by adki** [Xilinx/ml-suite#32]
I wonder if the YOLO2 with ML-Suite can handle video stream input, e.g., USB camera or files.
There was a demo called 'Deep Detect' - DeepDetect Webcam Tutorial, but it is not found in current ML Suite. (https://github.com/Xilinx/ml-suite/blob/master/docs/tutorials/deepdetect_webcam.md)

Thanks. Ando.

**Comment by adu81020799** [comment]
Hello,
Even I am looking for the same tutorial.cant find it.

**Comment by wilderfield** [comment]
Our webcam demo needs a refresh. Hopefully we get to it soon. Stay tuned...

**Comment by wilderfield** [comment]
Hey, we have moved away from the deepdetect demo, because it used a lot of outdated APIs. You can build your own webcam app using the example application we share in apps/REST

It’s a simple rest server that listens for requests, and sends back classifications.
