### ISSUE TITLE
Running Yolo / ML Suite with AWS F1

### ISSUE THREAD

**Issue by adki** [Xilinx/ml-suite#39]
I spent several weeks to run YOLO / ML Suite on AWS F1 and finally I can see the results. I did not try any change on the design and I just wanted to run and see the result. The reason why it made me spend such a long time is that I was a beginner for AWS and I tried to use SDAccel (github.com/Xilinx/SDAccel_Examples) on AWS F1 at the same time, since ML Suite relies on SDAccel. Even I already have an experience with SDAccel on local machine, I had a number of errors related with AWS environment.
Anyway, I prepared a getting started [yolo_on_aws_f1.pdf](https://github.com/Xilinx/ml-suite/files/2365825/yolo_on_aws_f1.pdf) and hope it will help those who getting troubles while running YOLO / ML suite.

Thanks to all who gave hep on the issues I raised.

**Comment by wilderfield** [comment]
Wow!! Thanks for this contribution!!

**Comment by durgabhavaniv** [comment]
Thank you
