### ISSUE TITLE
"git lfs pull" error (This repository is over its data quota)

### ISSUE THREAD

**Issue by valuefish** [Xilinx/ml-suite#40]
Getting an error if try `git lfs pull` afterward:
```shell
$ git lfs pull
batch response: This repository is over its data quota. Purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/Xilinx/ml-suite.git/info/lfs'
```

**Comment by wilderfield** [comment]
Thanks for reporting this. We will fix and get back to you.

**Comment by valuefish** [comment]
@wilderfield Thanks for your reply. I just tried again, still get the same problem. Hope it can be solved sooner.

**Comment by computingdolas** [comment]
I am also facing the same issue :)

**Comment by duclongpl** [comment]
@wilderfield : Hi , we want to run some examples on this.
But we also got this issue. So could you let me know when this issue is fixed ?
Regards,
Long.

**Comment by wilderfield** [comment]
To anyone having this problem, please email bryanloz@xilinx.com and I will
personally send you a tarball with the models directory.

We are having to move away from git lfs, because of this recurring problem.
In my opinion, git lfs is unusable, because of how it is being monetized.

Sorry, for the trouble,
Bryan

**Comment by computingdolas** [comment]
Hello Bryan, 

I am looking forward to test Xilinx machine learning suite on Amazon EC-2 instances. Would it be possible to also let us know what will be the work around if you send the models personally to each of us ? 

Regards,
Sagar

**Comment by huytu36** [comment]
a question I have ever encountered in Xilinx. And I'm looking for answers.

**Comment by kamranjk** [comment]
Hi All,

Please dope a note on this thread on our [Xilinx Forum](https://forums.xilinx.com/t5/Xilinx-ML-Suite/Clone-Error-Smudge-error-repository-over-its-data-quota/td-p/889650) and i will send you the models directly. 

Thanks,
Kamran

**Comment by wilderfield** [comment]
Hi All,

We have moved away from git-lfs due to these problems.

You can get the models directory from here:
https://www.xilinx.com/member/forms/download/ml-suite-eula-xef.html?filename=models.zip

You will need to setup a xilinx username / password if you don't have one.
