### ISSUE TITLE
Running a profiler through XCL bins file

### ISSUE THREAD

**Issue by adu81020799** [Xilinx/ml-suite#45]
I wanted to to get the power and area estimates for the XCL bins files for which I need to create a new XCL bin file. Is there any guide which would describe how to generate these files?
Regards
Adarsh

**Comment by adu81020799** [comment]
Is there a way to generate a custom XCL bin fine for aws ??

**Comment by wilderfield** [comment]
https://github.com/aws/aws-fpga
