### ISSUE TITLE
error :running the quantizer for tinydarknet

### ISSUE THREAD

**Issue by adu81020799** [Xilinx/ml-suite#50]
Hello,
I was trying to run the quantizer for the tiny dark net .I have following two questions
 I have used the weight file generated from after I run the compiler (generated as tinyDarkoptimized ). When I run the quantizer I get following error:
Processing layer 7 of 37
Layer Name:layer5-conv Type:Convolution
Inputs: ['layer4-maxpool'], Outputs: ['layer5-conv']
Quantizing conv input layer ... layer5-conv
Threshold in shape= ()
Quantizing conv weights for layer layer5-conv...
Threshold params shape= (16,)
Min:  0 , Max:  nan
Failed to quantize: range parameter must be finite.

1)I am not sure about the error and I cant examine this error as I donot have a .py file.

2)Do I need to use the weight file generated only through the quantizer or can i directly use the .caffe models which I generated through the darknettocaffe script as the weight file size is already small (around 4mb) and run inference without quantizing ?

**Comment by wilderfield** [comment]
1) There are ways to debug without having the *.py; although ideally you shouldn’t have to debug

2) The purpose of quantization is actually to run integer arithmetic instead of floating point in order to achieve higher OPS. So you need to quantize
