### ISSUE TITLE
FPGA Developer AMI 1.5 (Please stay on 1.4)

### ISSUE THREAD

**Issue by wilderfield** [Xilinx/ml-suite#52]
FPGA Developer AMI 1.5 was tested with ml-suite for the first time today.

I am seeing some issue with the Xilinx runtime which comes preinstalled in the AMI.

Please hold off developing with this AMI, and use version 1.4

**Comment by kamranjk** [comment]
Put this as a FAQ and a note on the release note. im closing this.
