### ISSUE TITLE
 compile error unsupported operand type(s)

### ISSUE THREAD

**Issue by luckyteddy** [Xilinx/ml-suite#53]
Hi,

I tried to use the compiler xfdnn_compiler_caffe.pyc to compile bvlc_googlenet_without_lrn_deploy.prototxt.
It pops out

**************************************************
* COMPUTING MEMORY REQUIREMENTS
**************************************************
ParametersLayer(type=[u'Pooling'], number_outputs=None, paddings=[[]], kernel_sizes=[[3L]], strides=[[2L]], dilation=None, group=None, shapes=None, sizes=None, quantizations=None, batches=None, layer_type=['layer'], extras_and_future=None, tops=[u'pool1/3x3_s2'], bottoms=[u'conv1/7x7_s2'], layer=[name: "pool1/3x3_s2"
type: "Pooling"
bottom: "conv1/7x7_s2"
top: "pool1/3x3_s2"
pooling_param {
  pool: MAX
  kernel_size: 3
  stride: 2
}
], dag=ColorForDAG(active=[0], schedule=3, forward=[4], backward=[1, 2], extra=None, hook=[]), systolic_width=None, word_width=None, alignedsizes=None, bias=None, scale=None, preshift=None, postshift=None, batchnormalization=None, relu=None, fcmode=None, pool=0, operation=None, scaling=None, data=None, name=u'pool1/3x3_s2', input_addresses=None, output_addresses=None, data_movements=None, data_movement_costs=None, instructions=None, tf_pad=None)
Failed to complete compilation: unsupported operand type(s) for *: 'int' and 'RepeatedScalarFieldContainer'

**Comment by luckyteddy** [comment]
found that the kernel_sizes of pooling layer is [[3L]] instead of [3L], so the p.kernel_size[0] return wrong type

**Comment by wilderfield** [comment]
Try again, use examples/compile/xfdnn_compiler_caffe_bvlc*.sh as an example.

This should work.
