### ISSUE TITLE
How to handle multiple FC layers before softmax/sigmoid?

### ISSUE THREAD

**Issue by eerobert** [Xilinx/ml-suite#63]
1. in GoogleNet example, how to access fcWeight/fcBias for particular layer as input?
2. can the return data from computeFC pass on to another computeFC?
3. can print the data value of computeFC output?

**Comment by wilderfield** [comment]
1. fcWeight, fcBias = xdnn_io.loadFCWeightsBias(args)
2. Yes
3. Yes; print fcOutput

Take a look at latest test_classify.py
