### ISSUE TITLE
image_classification_caffe.ipynb failed

### ISSUE THREAD

**Issue by eerobert** [Xilinx/ml-suite#69]
When I run to Step 10. Execute the Fully Connected Layers on the CPU, the kernel failed.

How do I debug the problem?

Thanks

**Comment by eerobert** [comment]
Thanks for your answer but it didn't help much.

**Comment by eerobert** [comment]
I would like to know the API of computeFC since the source code is not available in v1.3
otherwise, it cannot be debug further.

**Comment by eerobert** [comment]
any update from xilinx?

**Comment by eerobert** [comment]
any update from xilinx?

**Comment by mahinlma** [comment]
@eerobert, 
You can check computeFC API here [computeFC](http://xilinx.ai/_modules/xfdnn/rt/xdnn.html#computeFC)

**Comment by durgabhavaniv** [comment]
Hi @eerobert 

For running image classification on terminal for caffe model, You can go through the below link.
https://github.com/durgabhavaniv/ml-suite/blob/master/docs/image_classifier_terminal_caffe.md

Please comment if you are facing some issues.

**Comment by wilderfield** [comment]
Invocation from xdnn.py:
```
self._lib.computeFC(weight, bias, data, M, N, K, out)
```

This is the C++ code which we don't release (we only release the library):
```
void computeFC(float *weight, float *bias, float *data,
    int M, int N, int K, float *output)
{
  // Caffe provides transposed weights
  int lda = K;
  int ldb = K;

  cblas_sgemm(CblasRowMajor,
      (CBLAS_TRANSPOSE)CblasNoTrans, (CBLAS_TRANSPOSE)CblasTrans,
      M, N, K, 1.,
      data, lda, weight, ldb, 0., output, N);

  // bias is not transposed
  lda = 1;
  ldb = N;
  std::vector<float> bias_multiplier(M, 1.);

  cblas_sgemm(CblasRowMajor,
      (CBLAS_TRANSPOSE)CblasNoTrans, (CBLAS_TRANSPOSE)CblasNoTrans,
      M, N, 1, 1.,
      &(bias_multiplier[0]), lda, bias, ldb, 1., output, N);
}
```

As you can see we are just making straight calls to the blas library. If it doesn't work there just happens to be a system / environment problem.
