### ISSUE TITLE
offline application

### ISSUE THREAD

**Issue by anguoyang** [Xilinx/ml-suite#7]
Hi, thanks for your great contribution, I have a question:
is it possible to implement deep learning on xilinx without AWS, I mean, run all DL related application with caffe(or mxnet) ONLY on the FPGA board.
Sorry that I am not familiar with FPGA, but I have strong willing(also with good experience) on deep learning, I am C/C++ programmer.
Thank you.

**Comment by kamranjk** [comment]
Hi, 
Yes that is possible. Currently, we also support the same software stack and features for the [Xilinx VCU1525 PCIe card](https://www.xilinx.com/products/boards-and-kits/vcu1525-a.html). 

What types of applications are you working on? 

Thanks,
kamran

**Comment by durgabhavaniv** [comment]
Hi, as you given flow and webinar session for aws f1, in the same way can i get it for my own vcu1525 pack card.
