### ISSUE TITLE
xdnn.computeFC cause kernel dead

### ISSUE THREAD

**Issue by eerobert** [Xilinx/ml-suite#79]
When running image_classification_caffe.ipynb, the kernel reported to be dead when executing the xdnn.computeFC.

I believe it is library outdated with the argument list changed.
Please update the corresponding library

**Comment by wilderfield** [comment]
Most likely this means that you are running on a machine that does not support AVX2 instructions. Our library has OpenBLAS statically linked, and we compiled the OpenBLAS library for AVX2. This has caused some problems on older machines when people try to run computeFC. A work around is to not use the function, and write your own FC layer with python's numpy. In fact... we were using numpy in earlier versions of ml-suite. You might be able to steal the code, by looking at older versions of xfdnn/rt/xdnn.py
