### ISSUE TITLE
missing links

### ISSUE THREAD

**Issue by gguasti** [Xilinx/ml-suite#91]
https://github.com/Xilinx/ml-suite/blob/master/docs/ml-suite-overview.md has some missing links:

[overlay selector guide](https://github.com/Xilinx/ml-suite/blob/overlaybins/README.md) 
[xfDNN tool notebooks](https://github.com/Xilinx/ml-suite/blob/docs/tutorials/README.md)

**Comment by wilderfield** [comment]
Thanks @gguasti I've fixed this in our internal repository. The docs will work in the next release. The overlay selector guide is at ml-suite/overlaybins/README.md the relative link was incorrect. Thanks again.
